import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { API } from '../globals';
import { environment } from '../../environments/environment';
import { ProviderHubService } from '../app.service';
import { CommonModule, Location } from '@angular/common';
import { GenderPipe, NullablePipe, BoolPipe, SpecialtyTypePipe, ParentSpecialtyPipe, NoValuePipe, PHDatePipe, PhoneToDBPipe, PhoneFromDBPipe } from '../pipes';
import * as $ from 'jquery';
import 'datatables.net';
import 'datatables.net-bs4';
import 'datatables.net-select-bs4';
import 'jquery-ui-bundle';

@Component({
  selector: 'app-facility',
  templateUrl: './facility.component.html',
  styleUrls: ['./facility.component.scss']
})
export class FacilityComponent implements OnInit {

  public apiRoot: string;
  public facilityId: number;
  public initialTab: string = "";
  public Facility: any;
  public FacilityAddress: any;
  public Service: any;
  public nav: string;
  public providerDT: any;
  public editingDivWrappers: any;
  public editingDivHeaderWrappers: any;
  public editingHeaderDivs: any;

  constructor(private route: ActivatedRoute, private router: Router,
    private service: ProviderHubService, private location: Location) {
    this.Service = service; this.Facility = {}; this.FacilityAddress = {};
    //TEST FACILITY FOR DEBUG
    this.nav = 'Demographics';//default=Demographics, change to test
  }

  ngOnInit() {
    this.apiRoot = environment.apiRoot; var _dis = this; var toClick = null;
    this.route.params.subscribe(params => {
      this.facilityId = +params['id'];
      if (params['tabURL']) { this.initialTab = params['tabURL']; } else {
        this.location.replaceState("/Facility/Demographics/" + this.facilityId);
      }
    });
    var navs = document.getElementById("facility-nav").getElementsByTagName("li");
    for (var i = 0; i < navs.length; i++) {
      navs[i].addEventListener("click", (function (event) {
        return function (e) {
          _dis.nav = this.getAttribute("tab-id");
          _dis.location.replaceState("/Facility/" + this.getAttribute("tab-url") + "/" + _dis.facilityId);
          if (_dis.nav != 'Providers') { $("#providersTableDT_wrapper").hide(); } else { $("#providersTableDT_wrapper").show(); } /*cant do in Angular since generated by DT*/
        }
      })(_dis), false);
      if (navs[i].getAttribute("tab-url") == this.initialTab) { toClick = navs[i] as HTMLElement; }
    }
    if (this.initialTab != "") { toClick.click(); }

    this.editingDivWrappers = ['#facility-demo', '#demoTable'];
    this.editingDivHeaderWrappers = ['#facility-main-header', '#demo-card .card-title'];
    this.editingHeaderDivs = [document.getElementById("facility-main-header"), document.getElementById("demo-card").getElementsByClassName('card-title')[0]];

    //0=PROVIDER HEADER EDIT, 1=PROVIDER DEMO EDIT
    for (var i = 0; i < this.editingHeaderDivs.length; i++) {
      (function () {
        var divs = _dis.editingHeaderDivs[i]; var _i = i;
        divs.getElementsByClassName("not-editing")[0].addEventListener("click", function (event) { //edit
          _dis.editFacility(_i, event);
        });
        divs.getElementsByClassName("is-editing")[0].addEventListener("click", function (event) { //save
          _dis.saveFacility(_i, event);
        });
        divs.getElementsByClassName("is-editing")[1].addEventListener("click", function (event) { //cancel
          _dis.cancelEdit(_i, event);
        });
      })();
    }

    this.service.hitAPI(this.apiRoot + "Facility/ByID/" + this.facilityId).subscribe(
      data => {
        //0. Edit/Save buttons and Misc UI
        for (var i = 0; i < this.editingDivWrappers.length; i++) {
          let _editDivs: any = $(this.editingDivHeaderWrappers[i] + " i.is-editing," + this.editingDivWrappers[i] + " .is-editing"); _editDivs.hide(); _editDivs = null;
          let _notEditDivs: any = $(this.editingDivHeaderWrappers[i] + " i.not-editing," + this.editingDivWrappers[i] + " .not-editing"); _notEditDivs.show(); _notEditDivs = null;
        }
        //1. header and address
        this.Facility = data; this.FacilityAddress = this.Facility.FacilityAddress;
        document.getElementById("page-title").innerHTML = this.Facility.FacilityName;
        this.Facility.LastUpdatedDate = new PHDatePipe().transform(this.Facility.LastUpdatedDate.replace(/\D/g, '').slice(0,-4));
        this.FacilityAddress.AddressLine1 = (this.FacilityAddress.AddressLine1 == null) ? "" : this.FacilityAddress.AddressLine1;
        this.FacilityAddress.AddressLine2 = (this.FacilityAddress.AddressLine2 == null) ? "" : this.FacilityAddress.AddressLine2;
        //1b. specs
        for (var i = 0; i < this.Facility.FacilitySpecialties.length; i++) {
          var s = this.Facility.FacilitySpecialties[i];
          s.EffectiveDate = s.EffectiveDate.replace(/\D/g, '').slice(0, -4);
          s.TerminationDate = (s.TerminationDate == null) ? '' : s.TerminationDate.replace(/\D/g, '').slice(0, -4);
          s.LastUpdatedDate = (s.LastUpdatedDate == null) ? '' : s.LastUpdatedDate.replace(/\D/g, '').slice(0, -4);
        }
        let list: any = $('#specList'); list.sortable();
        let providersLink: any = $("#facility-nav li[tab-id='Providers']");
        providersLink.click(function () {
          if (typeof (Event) === 'function') { window.dispatchEvent(new Event('resize')); }
          else { var evt = window.document.createEvent('UIEvents'); evt.initUIEvent('resize', true, false, window, 0); window.dispatchEvent(evt); }
        });
        //2. providers
        for (var i = 0; i < this.Facility.FacilityProviders.length; i++) {
          var _c = this.Facility.FacilityProviders[i].CredentialListStr;
          this.Facility.FacilityProviders[i].Credentials = (_c==null)? "" : _c.slice(0, -1).replace(/,/g,", ");
        }
        let providersDTID: any = $('#providersTableDT');
        this.providerDT = providersDTID.DataTable({
          select: true,
          paging: false,
          language: { search: "", searchPlaceholder: "Begin typing in a Provider Name or NPI to filter search results" },
          data: this.Facility.FacilityProviders,
          columns: [{ data: null, orderable: false,searchable:false,defaultContent:''},
          { data: "NPI" }, { data: "LastName" }, { data: "FirstName" },
          { data: null, render: function (data, type, row) { var d = data.CredentialListStr; return (d == null) ? "" : d.slice(0, -1).replace(/,/g, ", "); }, searchable: false },
          { data: null, render: function (data, type, row) { var d = data; var r; switch (d.Gender) { case 1: r = "Female"; break; case 2: r = "Male"; break; default: r = " "; break; } return r; }, searchable: false },
          { data: null, render: function (data, type, row) { var d = data.PrimarySpecialty; return d; }, searchable: false },
          { data: null, render: function (data, type, row) { var d = data; return ""; }, searchable: false }
          ],
          order: [[1, "asc"]],
          rowId: 'ID',
          initComplete: function (settings, json) {
            if (_dis.nav != 'Providers') { $("#providersTableDT_wrapper").hide(); } else { $("#providersTableDT_wrapper").show(); } /*cant do in Angular since generated by DT*/
            if (typeof (Event) === 'function') { window.dispatchEvent(new Event('resize')); }
            else { var evt = window.document.createEvent('UIEvents'); evt.initUIEvent('resize', true, false, window, 0); window.dispatchEvent(evt); }
          }
        });
        this.providerDT.on('select',
          (e, dt, type, indexes) => {
            console.log(this.providerDT.rows(indexes).data().pluck("ID"));
            this.onRowSelect(this.providerDT.rows(indexes).data().pluck("ID"));
          }
        );
        this.providerDT.on('deselect',
          (e, dt, type, indexes) => {
            console.log(this.providerDT.rows(indexes).data().pluck("ID"));
            this.onRowSelect(this.providerDT.rows(indexes).data().pluck("ID"));
          }
        );
        //2b. Vendor 
        // Facility-level properties to set from Vendor: VendorName ([0].VendorName) | VLastUpdatedBy ([0].LastUpdatedBy) | VLastUpdatedDate ([0].LastUpdatedDate)
        this.Facility.VendorName = this.Facility.VendorAddresses[0].VendorName;
        this.Facility.VID = this.Facility.VendorAddresses[0].VID;
        this.Facility.VLastUpdatedBy = this.Facility.VendorAddresses[0].LastUpdatedBy;
        this.Facility.VLastUpdatedDate = new PHDatePipe().transform(this.Facility.VendorAddresses[0].LastUpdatedDate.replace(/\D/g, '').slice(0, -4));
        // Any tweaking of vendor properties needed: mess with this.Facility.VendorAddresses[i] -- do for PhoneExtension and AlternatePhoneNumber
        //3. Additional properties for UI conditionals ('novalue' pipe doesn't work??)
        this.FacilityAddress.HidePhoneExtension = (this.FacilityAddress.PhoneExtension == null || this.FacilityAddress.PhoneExtension == '');
        this.FacilityAddress.HideAlternatePhoneNumber = (this.FacilityAddress.AlternatePhoneNumber == null || this.FacilityAddress.AlternatePhoneNumber == '');
        this.FacilityAddress.HideAltExtension = (this.FacilityAddress.AlternateExtension == null || this.FacilityAddress.AlternateExtension == '');
        /*this.providerDT.on('search.dt', () => {
          document.getElementById('providersTableDT').getElementsByTagName('tbody')[0].style.visibility = (document.getElementById('providersTableDT_filter').getElementsByTagName('input')[0].value.length < 2) ? "hidden" : "visible";
        });
        document.getElementById('providersTableDT').getElementsByTagName('tbody')[0].style.visibility = (document.getElementById('providersTableDT_filter').getElementsByTagName('input')[0].value.length < 2) ? "hidden" : "visible";*/
      }
    );
    document.getElementById("page-title").innerHTML = API.selectedFacility;
  }
  public onSpecClick(event: any) {
    $(event.target).parent().children("table.specTable").toggle();
    $(event.target).parent().parent().children(".provSpecFooter,.provFacFooter").toggle();
  }
  private onRowSelect(indexes: number[]): void {
    var providerId = indexes[0];
    console.log(providerId);
    console.log($("tr#" + providerId));
    var row = this.providerDT.row($("tr#" + providerId)[0]);
    if (row.child.isShown()) {
      row.child.hide();
    } else {
      row.child(format(row.data()),'expandedFP').show();
    }
    function format(d) {
      return "<table class='plainjane'>" + "<tr><td><a href='../provider/"+d.ID+"'>View Provider</a></td>"
        + "<td><span class='childRowHeader'>External Provider</span> <br/>" + new BoolPipe().transform(d.FPRelationship.ExternalProviderIndicator) + "</td>"
        + "<td><span class='childRowHeader'>Accepting New Patients</span> <br/>" + new BoolPipe().transform(d.FPRelationship.AcceptingNewPatientIndicator) + "</td>"
        + "<td><span class='childRowHeader'>Prescriber</span> <br/>" + new BoolPipe().transform(d.FPRelationship.PrescriberIndicator) + "</td>"
        + "<td><span class='childRowHeader'>Referral</span> <br/>" + new BoolPipe().transform(d.FPRelationship.ReferralIndicator) + "</td>"
        //+ "<td>PCP Eligible <br/>" + new BoolPipe().transform(d.FPRelationship.PCPEligibleIndicator) + "</td>" BRANDON - Moved to Directory Table. Safe to delete this row of code -SKP
        + "<td><span class='childRowHeader'>Float Provider</span> <br/>" + new BoolPipe().transform(d.FPRelationship.FloatProviderIndicator) + "</td></tr>";
    }
  }
  //save/edit Facility for Main/Demographics
  public saveFacility(type: number, event: any) {
    let _editDivs: any = $(this.editingDivHeaderWrappers[type] + " i.is-editing," + this.editingDivWrappers[type] + " .is-editing"); _editDivs.hide(); _editDivs = null;
    let _notEditDivs: any = $(this.editingDivHeaderWrappers[type] + " i.not-editing," + this.editingDivWrappers[type] + " .not-editing"); _notEditDivs.show(); _notEditDivs = null;
    this.loading(true, type);//load starting, show overlay
    function val(which) { let _e: any = $("#edit_Facility_" + which); return _e.val(); }//MULTI SELECT VALS ARE ID ARRAYS
    function val2(which) { let _e: any = $("#edit_FacilityDemo_" + which); return _e.val(); } let body: any;
    switch (type) {
      case 0: //"Main" Facility-Header Info
        body = { Name: val("Name"), NPI: val("NPI"), User: environment.authUser.username };
        break;
      case 1: //Demographics (Really just an address)
        var phoneFixer = new PhoneToDBPipe();
        body = { Address1: val2("Address1"), Address2: val2("Address2"), City: val2("City"), State: val2("State"), Zip: val2("ZipCode"), User: environment.authUser.username };
        body.PhoneNumber = phoneFixer.transform(val2("PhoneNumber")); body.PhoneExtension = val2("PhoneExtension");
        body.AlternatePhoneNumber = phoneFixer.transform(val2("AltNumber")); body.AlternateExtension = val2("AltExtension");
        if (isNaN(body.PhoneNumber) || isNaN(body.AlternatePhoneNumber)) { alert("Invalid Phone Number. (must be 10 digit number, leading +1 allowed, dashes and parentheses allowed)"); return; }
        body.FaxNumber = val2("FaxNumber"); body.Website = val2("Website");
        break;
      case 2: //Specialties
        break;
      default: //log error + weird behavior
        break;
    }
    console.log(body);
    this.service.hitAPI(this.apiRoot + "Facility/Save/" + type + "/" + this.facilityId, JSON.stringify(body)).subscribe(
      data => {
        console.log(data); this.loading(false, data.POSTvars.type);//load finished, hide overlay
        switch (data.POSTvars.type) {
          case 0:
            //header data to just transform over (replace with partial arr matching function)
            this.Facility.FacilityName = data.POSTvars.Name; this.Facility.NPI = data.POSTvars.NPI;
            break;
          case 1:
            //demo data to just transform over (also replace with partial arr matching fxn)
            this.FacilityAddress.AddressLine1 = data.POSTvars.Address1; this.FacilityAddress.AddressLine2 = data.POSTvars.Address2;
            this.FacilityAddress.City = data.POSTvars.City; this.FacilityAddress.State = data.POSTvars.State; this.FacilityAddress.ZipCode = data.POSTvars.Zip;
            this.FacilityAddress.PhoneNumber = data.POSTvars.PhoneNumber; this.FacilityAddress.PhoneExtension = data.POSTvars.PhoneExtension;
            this.FacilityAddress.AlternatePhoneNumber = data.POSTvars.AlternatePhoneNumber; this.FacilityAddress.AlternateExtension = data.POSTvars.AlternateExtension;
            this.FacilityAddress.FaxNumber = data.POSTvars.FaxNumber; this.FacilityAddress.Website = data.POSTvars.Website;
            this.FacilityAddress.HideAlternatePhoneNumber = (data.POSTvars.AlternatePhoneNumber.trim() == "");
            this.FacilityAddress.HideAltExtension = (data.POSTvars.AlternateExtension.trim() == "");
            this.FacilityAddress.HidePhoneExtension = (data.POSTvars.PhoneExtension.trim() == "");
            break;
          case 2:
            break;
          default: //log error + weird behavior
            break;
        }
      }
    );
  }

  public editFacility(type: number, event: any) {
    let _editDivs: any = $(this.editingDivHeaderWrappers[type] + " i.is-editing," + this.editingDivWrappers[type] + " .is-editing"); _editDivs.show(); _editDivs = null;
    let _notEditDivs: any = $(this.editingDivHeaderWrappers[type] + " i.not-editing," + this.editingDivWrappers[type] + " .not-editing"); _notEditDivs.hide(); _notEditDivs = null;
  }

  public cancelEdit(type: number, event: any) {
    let _editDivs: any = $(this.editingDivHeaderWrappers[type] + " i.is-editing," + this.editingDivWrappers[type] + " .is-editing"); _editDivs.hide(); _editDivs = null;
    let _notEditDivs: any = $(this.editingDivHeaderWrappers[type] + " i.not-editing," + this.editingDivWrappers[type] + " .not-editing"); _notEditDivs.show(); _notEditDivs = null;
  }

  public loading(isLoading, saveType) {
    let loadOverlay: any = $("#loadOverlay" + saveType);
    if (isLoading) { loadOverlay.show(); } else { loadOverlay.hide(); }
  }

}
